--- 
format:
  dashboard:
    orientation: columns

css: styles.css
---

```{r setup, include=FALSE}

#library(flexdashboard)
library(tidyverse)
library(highcharter)
library(gt)
library(htmltools)
library(viridis)
library(readr)

```

```{r}
#import data

df <- read_csv("~/R/COde/andriiskandar/bestsellers with categories.csv", show_col_types = FALSE)

#Remove duplicate

df <- df %>% 
  distinct(Name, .keep_all = TRUE) %>% 
  rename("user_rating" = `User Rating` )

```


## Column {.tabset .tabset-pills-right width=60% .my-left-column}


```{r}

# Colors
custom_colors <- viridis::mako(n = 15)

# Most popular authors by reviews
df %>% 
  group_by(Author) %>% 
  summarise(Reviews = sum(Reviews)) %>% 
  arrange(desc(Reviews)) %>% 
  head(15) %>% 
  hchart('column', hcaes(x = Author, y = Reviews,color = custom_colors)) %>%
  hc_add_theme(hc_theme_google()) %>% 
  hc_tooltip(pointFormat = '<b>Number of Reviews: </b> {point.y} <br>') %>% 
  hc_title(text = 'Most Popular Authors from 2009 to 2019',
           style = list(fontSize = '25px', fontWeight = 'bold')) %>% 
  hc_subtitle(text = 'By Number of Reviews',
              style = list(fontSize = '16px')) %>% 
  hc_credits(enabled = TRUE, text = '@miguelfzzz')
```

```{r}

# Colors
custom_colors <- viridis::plasma(n = 15)

# Most popular books by reviews
df %>% 
  arrange(desc(Reviews)) %>% 
  head(15) %>% 
  hchart('bar', hcaes(x = Name, y = Reviews, color = custom_colors)) %>% 
  hc_add_theme(hc_theme_google()) %>% 
  hc_tooltip(pointFormat = '<b>Number of Reviews: </b> {point.y} <br>') %>% 
  hc_title(text = 'Most Popular Books from 2009 to 2019',
           style = list(fontSize = '25px', fontWeight = 'bold')) %>% 
  hc_subtitle(text = 'By Number of Reviews',
              style = list(fontSize = '16px')) %>% 
  hc_credits(enabled = TRUE, text = '@miguelfzzz')

```

```{r}

# Colors
custom_colors <- viridis::mako(n = 15)

# Most popular authors by reviews

df %>% 
  group_by(Year, Genre) %>% 
  summarise(total = n(), .groups = "drop") %>% 
  group_by(Genre) %>% 
  mutate(cummulative = cumsum(total)) %>% 
  hchart('line', hcaes(x = Year, y = cummulative, color = Genre, group = Genre)) %>%
  hc_add_theme(hc_theme_google()) %>% 
  hc_tooltip(pointFormat = '<b>Books produced: </b> {point.y} <br>') %>% 
  hc_title(text = 'Cummulative Books Produced Year-to-Year',
           style = list(fontSize = '25px', fontWeight = 'bold')) %>% 
  hc_subtitle(text = 'Non Fiction still leads',
              style = list(fontSize = '16px')) %>% 
  hc_credits(enabled = TRUE, text = 'inspired by @miguelfzzz')

```

## Column {width=40%}

```{r}

# This is going to be a datatable

df1 <- df %>% 
  filter(user_rating >= 4.9) %>% 
  arrange(desc(Reviews)) %>% 
  select(Name, Author, Price)

# HTML table
div(style = 'height:600px; overflow-y:scroll', gt(df1) %>% 
      tab_header(title = md('Best Books from 2009 to 2019'),
                 subtitle = md('By Users Rating >= 4.9')) %>% 
      opt_table_font(font = list(google_font('Chivo'), default_fonts())) %>% 
      tab_style(location = cells_column_labels(columns = everything()),
                style = list(cell_borders(sides = 'bottom', 
                                          weight = px(2)), 
                             cell_text(weight = 'bold'))) %>% 
      tab_options(table.font.size = px(12L),
                  table.border.top.style = 'none',
                  column_labels.border.bottom.width = 2,
                  table_body.border.top.style = 'none',
                  data_row.padding = px(3))
    )
```

```{r}
#| eval: false
#| include: false

# Colors

custom_colors <- viridis::mako(n = 2)

# Most common genre

df %>%
  group_by(Genre) %>%
  summarise(count = n()) %>%
  hchart('pie', hcaes(x = Genre, y = count, color = custom_colors)) %>%
  hc_add_theme(hc_theme_google()) %>%
  hc_tooltip(pointFormat='<b>Proportion: </b> {point.percentage:,.2f}%') %>%
  hc_title(text = 'Most Common Genre from 2009 to 2019',
           style = list(fontSize = '15px', fontWeight = 'bold')) %>%
  hc_credits(enabled = TRUE, text = '@miguelfzzz')

```